# Generated by Django 3.0.4 on 2020-03-24 03:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('sub_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_service_name', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesandrequests.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=120)),
                ('long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('people_capacity', models.IntegerField(blank=True, null=True)),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesandrequests.SubService')),
            ],
        ),
    ]
