# Generated by Django 3.0.4 on 2020-03-27 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesandrequests', '0005_auto_20200326_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='request',
            name='long',
        ),
        migrations.AddField(
            model_name='request',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicesandrequests.Area'),
        ),
        migrations.AddField(
            model_name='request',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicesandrequests.District'),
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicesandrequests.Service'),
        ),
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicesandrequests.State'),
        ),
    ]
